version: '3.8'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  express:
    container_name: express
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      NODE_ENV: 'PROD'
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    volumes:
      - static_volume:/home/app/static/

volumes: 
  db:
  static_volume:
